### ISSUE TITLE
Autopublishing SweetAlert

### ISSUE THREAD

**Issue by dandv** [MeteorPackaging/SweetAlert#1]
Hey @ecwyne and @kevohagan,

Would you like to work together to keep SweetAlert up-to-date using http://autopublish.meteor.com?

I see that https://github.com/kevohagan/meteor-sweetalert was updated 2 days ago.

@ecwyne wanted to help autopublish the wrapper - see https://github.com/MeteorPackaging/discussions/issues/29

Goals:
- Use autopublish
- Use the ["sister-repo" approach](https://github.com/MeteorPackaging/discussions/issues/16); @kevohagan already includes the upstream as a submodule rather than forking it - great
- Have only one authoritative SweetAlert package on Atmosphere

Namespacing-wise, I've created https://atmospherejs.com/sweetalert and added both of you, but [kevohagan:sweetalert](https://atmospherejs.com/kevohagan/sweetalert) already has a lot of traction on Atmosphere and
- until MDG implements renaming packages, we're probably better off keeping the existing naming
- on the other hand, the official twbs:boostrap easily overtook [@mizzao's bootstrap package](https://atmospherejs.com/mizzao/bootstrap-3) in popularity, with his graceful collaboration

**Comment by splendido** [comment]
[jspdf-core-wrapper](https://github.com/MeteorPackaging/jspdf-core-wrapper) might be the repo to look at  and copy paste files from it for a quick start! :-)

**Comment by kevohagan** [comment]
yes im totally up for this @dandv @ecwyne @splendido !

**Comment by kevohagan** [comment]
@dandv how to i go about doing the "sister-repo" aproach?

**Comment by splendido** [comment]
@kevohagan I've just seen you already [moved your repo to MeteorPackaging](https://github.com/MeteorPackaging/SweetAlert).

For the 'sister repo' approach, lets have a look at [jspdf-core-wrapper](https://github.com/MeteorPackaging/jspdf-core-wrapper): you basically have to copy/paste:
- gulpfile.js 
- package.json
- autopublish.json (to be edited...)

and update the `package.js` to have file paths referring to an `upstream` folder:

``` javascript
    api.add_files([
        'upstream/lib/sweet-alert.css',
        'upstream/lib/sweet-alert.min.js'
    ], ['client']);
```

this is because with `gulp getUpstream` a clone of the official repo will be made under the `upstream` folder.
This way you can get rid of the submodule and be able to checkout whichever version you need.

Whatmore, I'm finishing the integration for this new _approach_ right now, so that we can start testing it out.

The only missing thing to finish the process automation would be asking t4t5 to create a webhook for us...

**Comment by splendido** [comment]
See [this comment](https://github.com/MeteorCommunity/discussions/issues/14#issuecomment-111759843) for some instructions...

**Comment by ecwyne** [comment]
(sorry guys, I was out of town for a week)

@splendido I've updated the repo per your [comment](https://github.com/MeteorPackaging/SweetAlert/issues/1#issuecomment-111752569) (https://github.com/MeteorPackaging/SweetAlert/commit/1f0519634761f2417afbae5429b4cb2f74ce99b4)

**Comment by ecwyne** [comment]
> Whatmore, I'm finishing the integration for this new approach right now, so that we can start testing it out.

Is there anything else we need to do before this testing can begin?

**Comment by splendido** [comment]
I've also been out for more than a month...
I hope to be able to get back to autopublish.meteor.com soon

For now I'd say we'll have to keep it updated by hands.
Could you please try to publish the [new release](https://github.com/t4t5/sweetalert/releases/tag/v1.1.0) by hands?

There are still a couple fo things to be done though:
- update package name (`sweetalert:sweetalert`? or what?)
- update package summary to mention this is the _official_ wrapper
- add some tests (at least some [minimum tests like these](https://github.com/MeteorPackaging/jspdf-core-wrapper/tree/master/tests) to check `swal` is correctly exported...)

After this, the command sequence to publish a new version would be something like:
- `git clone https://github.com/MeteorPackaging/SweetAlert.git`
- `cd SweetAlert`
- `npm install`
- `gulp getUpstream --tag v1.1.0`
- `gult test`

and then, only in case tests pass:
- `gulp updateVersion`
- `gulp updateRelease --tag v1.1.0`
- `git commit -am 'Bump to version 1.1.0`
- `git push`
- `meteor publish` (`meteor publish --create` for this first time...)

**Comment by splendido** [comment]
Also, please consider to add another couple of files to correctly export `swal`...
See [these lines](https://github.com/MeteorPackaging/jspdf-core-wrapper/blob/master/package.js#L11-L15)

**Comment by splendido** [comment]
Let us know when you're ready to publish, just for a final check ;-)

**Comment by ecwyne** [comment]
This can probably be closed :)
